// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IMAuthService_GetAdminToken_FullMethodName    = "/openim.auth.IMAuthService/GetAdminToken"
	IMAuthService_GetUserToken_FullMethodName     = "/openim.auth.IMAuthService/GetUserToken"
	IMAuthService_ForceLogout_FullMethodName      = "/openim.auth.IMAuthService/ForceLogout"
	IMAuthService_ParseToken_FullMethodName       = "/openim.auth.IMAuthService/ParseToken"
	IMAuthService_InvalidateToken_FullMethodName  = "/openim.auth.IMAuthService/InvalidateToken"
	IMAuthService_KickTokens_FullMethodName       = "/openim.auth.IMAuthService/KickTokens"
	IMAuthService_GetExistingToken_FullMethodName = "/openim.auth.IMAuthService/GetExistingToken"
)

// IMAuthServiceClient is the client API for IMAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IMAuthServiceClient interface {
	// Generate token
	GetAdminToken(ctx context.Context, in *GetAdminTokenReq, opts ...grpc.CallOption) (*GetAdminTokenResp, error)
	// Admin retrieves user token
	GetUserToken(ctx context.Context, in *GetUserTokenReq, opts ...grpc.CallOption) (*GetUserTokenResp, error)
	// Force logout
	ForceLogout(ctx context.Context, in *ForceLogoutReq, opts ...grpc.CallOption) (*ForceLogoutResp, error)
	// Parse token
	ParseToken(ctx context.Context, in *ParseTokenReq, opts ...grpc.CallOption) (*ParseTokenResp, error)
	// Invalidate or mark the token as kicked out
	InvalidateToken(ctx context.Context, in *InvalidateTokenReq, opts ...grpc.CallOption) (*InvalidateTokenResp, error)
	// Kick tokens
	KickTokens(ctx context.Context, in *KickTokensReq, opts ...grpc.CallOption) (*KickTokensResp, error)
	// Get existing token
	GetExistingToken(ctx context.Context, in *GetExistingTokenReq, opts ...grpc.CallOption) (*GetExistingTokenResp, error)
}

type iMAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIMAuthServiceClient(cc grpc.ClientConnInterface) IMAuthServiceClient {
	return &iMAuthServiceClient{cc}
}

func (c *iMAuthServiceClient) GetAdminToken(ctx context.Context, in *GetAdminTokenReq, opts ...grpc.CallOption) (*GetAdminTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminTokenResp)
	err := c.cc.Invoke(ctx, IMAuthService_GetAdminToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMAuthServiceClient) GetUserToken(ctx context.Context, in *GetUserTokenReq, opts ...grpc.CallOption) (*GetUserTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTokenResp)
	err := c.cc.Invoke(ctx, IMAuthService_GetUserToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMAuthServiceClient) ForceLogout(ctx context.Context, in *ForceLogoutReq, opts ...grpc.CallOption) (*ForceLogoutResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceLogoutResp)
	err := c.cc.Invoke(ctx, IMAuthService_ForceLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMAuthServiceClient) ParseToken(ctx context.Context, in *ParseTokenReq, opts ...grpc.CallOption) (*ParseTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseTokenResp)
	err := c.cc.Invoke(ctx, IMAuthService_ParseToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMAuthServiceClient) InvalidateToken(ctx context.Context, in *InvalidateTokenReq, opts ...grpc.CallOption) (*InvalidateTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateTokenResp)
	err := c.cc.Invoke(ctx, IMAuthService_InvalidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMAuthServiceClient) KickTokens(ctx context.Context, in *KickTokensReq, opts ...grpc.CallOption) (*KickTokensResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickTokensResp)
	err := c.cc.Invoke(ctx, IMAuthService_KickTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMAuthServiceClient) GetExistingToken(ctx context.Context, in *GetExistingTokenReq, opts ...grpc.CallOption) (*GetExistingTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExistingTokenResp)
	err := c.cc.Invoke(ctx, IMAuthService_GetExistingToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMAuthServiceServer is the server API for IMAuthService service.
// All implementations must embed UnimplementedIMAuthServiceServer
// for forward compatibility.
type IMAuthServiceServer interface {
	// Generate token
	GetAdminToken(context.Context, *GetAdminTokenReq) (*GetAdminTokenResp, error)
	// Admin retrieves user token
	GetUserToken(context.Context, *GetUserTokenReq) (*GetUserTokenResp, error)
	// Force logout
	ForceLogout(context.Context, *ForceLogoutReq) (*ForceLogoutResp, error)
	// Parse token
	ParseToken(context.Context, *ParseTokenReq) (*ParseTokenResp, error)
	// Invalidate or mark the token as kicked out
	InvalidateToken(context.Context, *InvalidateTokenReq) (*InvalidateTokenResp, error)
	// Kick tokens
	KickTokens(context.Context, *KickTokensReq) (*KickTokensResp, error)
	// Get existing token
	GetExistingToken(context.Context, *GetExistingTokenReq) (*GetExistingTokenResp, error)
	mustEmbedUnimplementedIMAuthServiceServer()
}

// UnimplementedIMAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIMAuthServiceServer struct{}

func (UnimplementedIMAuthServiceServer) GetAdminToken(context.Context, *GetAdminTokenReq) (*GetAdminTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdminToken not implemented")
}
func (UnimplementedIMAuthServiceServer) GetUserToken(context.Context, *GetUserTokenReq) (*GetUserTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserToken not implemented")
}
func (UnimplementedIMAuthServiceServer) ForceLogout(context.Context, *ForceLogoutReq) (*ForceLogoutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceLogout not implemented")
}
func (UnimplementedIMAuthServiceServer) ParseToken(context.Context, *ParseTokenReq) (*ParseTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseToken not implemented")
}
func (UnimplementedIMAuthServiceServer) InvalidateToken(context.Context, *InvalidateTokenReq) (*InvalidateTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateToken not implemented")
}
func (UnimplementedIMAuthServiceServer) KickTokens(context.Context, *KickTokensReq) (*KickTokensResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickTokens not implemented")
}
func (UnimplementedIMAuthServiceServer) GetExistingToken(context.Context, *GetExistingTokenReq) (*GetExistingTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExistingToken not implemented")
}
func (UnimplementedIMAuthServiceServer) mustEmbedUnimplementedIMAuthServiceServer() {}
func (UnimplementedIMAuthServiceServer) testEmbeddedByValue()                       {}

// UnsafeIMAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMAuthServiceServer will
// result in compilation errors.
type UnsafeIMAuthServiceServer interface {
	mustEmbedUnimplementedIMAuthServiceServer()
}

func RegisterIMAuthServiceServer(s grpc.ServiceRegistrar, srv IMAuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedIMAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IMAuthService_ServiceDesc, srv)
}

func _IMAuthService_GetAdminToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMAuthServiceServer).GetAdminToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMAuthService_GetAdminToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMAuthServiceServer).GetAdminToken(ctx, req.(*GetAdminTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMAuthService_GetUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMAuthServiceServer).GetUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMAuthService_GetUserToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMAuthServiceServer).GetUserToken(ctx, req.(*GetUserTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMAuthService_ForceLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceLogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMAuthServiceServer).ForceLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMAuthService_ForceLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMAuthServiceServer).ForceLogout(ctx, req.(*ForceLogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMAuthService_ParseToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMAuthServiceServer).ParseToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMAuthService_ParseToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMAuthServiceServer).ParseToken(ctx, req.(*ParseTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMAuthService_InvalidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMAuthServiceServer).InvalidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMAuthService_InvalidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMAuthServiceServer).InvalidateToken(ctx, req.(*InvalidateTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMAuthService_KickTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickTokensReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMAuthServiceServer).KickTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMAuthService_KickTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMAuthServiceServer).KickTokens(ctx, req.(*KickTokensReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMAuthService_GetExistingToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExistingTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMAuthServiceServer).GetExistingToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMAuthService_GetExistingToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMAuthServiceServer).GetExistingToken(ctx, req.(*GetExistingTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IMAuthService_ServiceDesc is the grpc.ServiceDesc for IMAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.auth.IMAuthService",
	HandlerType: (*IMAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdminToken",
			Handler:    _IMAuthService_GetAdminToken_Handler,
		},
		{
			MethodName: "GetUserToken",
			Handler:    _IMAuthService_GetUserToken_Handler,
		},
		{
			MethodName: "ForceLogout",
			Handler:    _IMAuthService_ForceLogout_Handler,
		},
		{
			MethodName: "ParseToken",
			Handler:    _IMAuthService_ParseToken_Handler,
		},
		{
			MethodName: "InvalidateToken",
			Handler:    _IMAuthService_InvalidateToken_Handler,
		},
		{
			MethodName: "KickTokens",
			Handler:    _IMAuthService_KickTokens_Handler,
		},
		{
			MethodName: "GetExistingToken",
			Handler:    _IMAuthService_GetExistingToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
