// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: auth.proto
package auth

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// IMAuthServiceName is the fully-qualified name of the IMAuthService service.
	IMAuthServiceName = "openim.auth.IMAuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IMAuthServiceGetAdminTokenProcedure is the fully-qualified name of the IMAuthService's GetAdminToken RPC.
	IMAuthServiceGetAdminTokenProcedure = "/openim.auth.IMAuthService/GetAdminToken"
	// IMAuthServiceGetUserTokenProcedure is the fully-qualified name of the IMAuthService's GetUserToken RPC.
	IMAuthServiceGetUserTokenProcedure = "/openim.auth.IMAuthService/GetUserToken"
	// IMAuthServiceForceLogoutProcedure is the fully-qualified name of the IMAuthService's ForceLogout RPC.
	IMAuthServiceForceLogoutProcedure = "/openim.auth.IMAuthService/ForceLogout"
	// IMAuthServiceParseTokenProcedure is the fully-qualified name of the IMAuthService's ParseToken RPC.
	IMAuthServiceParseTokenProcedure = "/openim.auth.IMAuthService/ParseToken"
	// IMAuthServiceInvalidateTokenProcedure is the fully-qualified name of the IMAuthService's InvalidateToken RPC.
	IMAuthServiceInvalidateTokenProcedure = "/openim.auth.IMAuthService/InvalidateToken"
	// IMAuthServiceKickTokensProcedure is the fully-qualified name of the IMAuthService's KickTokens RPC.
	IMAuthServiceKickTokensProcedure = "/openim.auth.IMAuthService/KickTokens"
	// IMAuthServiceGetExistingTokenProcedure is the fully-qualified name of the IMAuthService's GetExistingToken RPC.
	IMAuthServiceGetExistingTokenProcedure = "/openim.auth.IMAuthService/GetExistingToken"
)

var (
	_ IMAuthService = (*IMAuthServiceImpl)(nil)
)

// IMAuthService is a client for the openim.auth.IMAuthService service.
type IMAuthService interface {
	GetAdminToken(ctx context.Context, req *GetAdminTokenReq, opts ...client.CallOption) (*GetAdminTokenResp, error)
	GetUserToken(ctx context.Context, req *GetUserTokenReq, opts ...client.CallOption) (*GetUserTokenResp, error)
	ForceLogout(ctx context.Context, req *ForceLogoutReq, opts ...client.CallOption) (*ForceLogoutResp, error)
	ParseToken(ctx context.Context, req *ParseTokenReq, opts ...client.CallOption) (*ParseTokenResp, error)
	InvalidateToken(ctx context.Context, req *InvalidateTokenReq, opts ...client.CallOption) (*InvalidateTokenResp, error)
	KickTokens(ctx context.Context, req *KickTokensReq, opts ...client.CallOption) (*KickTokensResp, error)
	GetExistingToken(ctx context.Context, req *GetExistingTokenReq, opts ...client.CallOption) (*GetExistingTokenResp, error)
}

// NewIMAuthService constructs a client for the auth.IMAuthService service.
func NewIMAuthService(cli *client.Client, opts ...client.ReferenceOption) (IMAuthService, error) {
	conn, err := cli.DialWithInfo("openim.auth.IMAuthService", &IMAuthService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &IMAuthServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerIMAuthService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &IMAuthService_ClientInfo)
}

// IMAuthServiceImpl implements IMAuthService.
type IMAuthServiceImpl struct {
	conn *client.Connection
}

func (c *IMAuthServiceImpl) GetAdminToken(ctx context.Context, req *GetAdminTokenReq, opts ...client.CallOption) (*GetAdminTokenResp, error) {
	resp := new(GetAdminTokenResp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetAdminToken", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *IMAuthServiceImpl) GetUserToken(ctx context.Context, req *GetUserTokenReq, opts ...client.CallOption) (*GetUserTokenResp, error) {
	resp := new(GetUserTokenResp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetUserToken", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *IMAuthServiceImpl) ForceLogout(ctx context.Context, req *ForceLogoutReq, opts ...client.CallOption) (*ForceLogoutResp, error) {
	resp := new(ForceLogoutResp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "ForceLogout", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *IMAuthServiceImpl) ParseToken(ctx context.Context, req *ParseTokenReq, opts ...client.CallOption) (*ParseTokenResp, error) {
	resp := new(ParseTokenResp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "ParseToken", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *IMAuthServiceImpl) InvalidateToken(ctx context.Context, req *InvalidateTokenReq, opts ...client.CallOption) (*InvalidateTokenResp, error) {
	resp := new(InvalidateTokenResp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "InvalidateToken", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *IMAuthServiceImpl) KickTokens(ctx context.Context, req *KickTokensReq, opts ...client.CallOption) (*KickTokensResp, error) {
	resp := new(KickTokensResp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "KickTokens", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *IMAuthServiceImpl) GetExistingToken(ctx context.Context, req *GetExistingTokenReq, opts ...client.CallOption) (*GetExistingTokenResp, error) {
	resp := new(GetExistingTokenResp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetExistingToken", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var IMAuthService_ClientInfo = client.ClientInfo{
	InterfaceName: "openim.auth.IMAuthService",
	MethodNames:   []string{"GetAdminToken", "GetUserToken", "ForceLogout", "ParseToken", "InvalidateToken", "KickTokens", "GetExistingToken"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*IMAuthServiceImpl)
		dubboCli.conn = conn
	},
}

// IMAuthServiceHandler is an implementation of the openim.auth.IMAuthService service.
type IMAuthServiceHandler interface {
	GetAdminToken(context.Context, *GetAdminTokenReq) (*GetAdminTokenResp, error)
	GetUserToken(context.Context, *GetUserTokenReq) (*GetUserTokenResp, error)
	ForceLogout(context.Context, *ForceLogoutReq) (*ForceLogoutResp, error)
	ParseToken(context.Context, *ParseTokenReq) (*ParseTokenResp, error)
	InvalidateToken(context.Context, *InvalidateTokenReq) (*InvalidateTokenResp, error)
	KickTokens(context.Context, *KickTokensReq) (*KickTokensResp, error)
	GetExistingToken(context.Context, *GetExistingTokenReq) (*GetExistingTokenResp, error)
}

func RegisterIMAuthServiceHandler(srv *server.Server, hdlr IMAuthServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &IMAuthService_ServiceInfo, opts...)
}

func SetProviderIMAuthService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &IMAuthService_ServiceInfo)
}

var IMAuthService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "openim.auth.IMAuthService",
	ServiceType:   (*IMAuthServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "GetAdminToken",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetAdminTokenReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetAdminTokenReq)
				res, err := handler.(IMAuthServiceHandler).GetAdminToken(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "GetUserToken",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetUserTokenReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetUserTokenReq)
				res, err := handler.(IMAuthServiceHandler).GetUserToken(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "ForceLogout",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(ForceLogoutReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*ForceLogoutReq)
				res, err := handler.(IMAuthServiceHandler).ForceLogout(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "ParseToken",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(ParseTokenReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*ParseTokenReq)
				res, err := handler.(IMAuthServiceHandler).ParseToken(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "InvalidateToken",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(InvalidateTokenReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*InvalidateTokenReq)
				res, err := handler.(IMAuthServiceHandler).InvalidateToken(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "KickTokens",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(KickTokensReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*KickTokensReq)
				res, err := handler.(IMAuthServiceHandler).KickTokens(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "GetExistingToken",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetExistingTokenReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetExistingTokenReq)
				res, err := handler.(IMAuthServiceHandler).GetExistingToken(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
