//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.1
// source: city/proto/mpaaspush.proto

package city_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_city_proto_mpaaspush_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_mpaaspush_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_city_proto_mpaaspush_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_city_proto_mpaaspush_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_mpaaspush_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_mpaaspush_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_city_proto_mpaaspush_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_mpaaspush_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_city_proto_mpaaspush_proto_rawDescGZIP(), []int{2}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hello         string                 `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_city_proto_mpaaspush_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_mpaaspush_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_mpaaspush_proto_rawDescGZIP(), []int{3}
}

func (x *SayHelloResponse) GetHello() string {
	if x != nil {
		return x.Hello
	}
	return ""
}

var File_city_proto_mpaaspush_proto protoreflect.FileDescriptor

const file_city_proto_mpaaspush_proto_rawDesc = "" +
	"\n" +
	"\x1acity/proto/mpaaspush.proto\x12\n" +
	"city_proto\"\"\n" +
	"\fGreetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\rGreetResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x10SayHelloResponse\x12\x14\n" +
	"\x05hello\x18\x01 \x01(\tR\x05hello2\x97\x01\n" +
	"\fGreetService\x12>\n" +
	"\x05Greet\x12\x18.city_proto.GreetRequest\x1a\x19.city_proto.GreetResponse\"\x00\x12G\n" +
	"\bSayHello\x12\x1b.city_proto.SayHelloRequest\x1a\x1c.city_proto.SayHelloResponse\"\x00BZ\n" +
	"\x15city.java.mpaas.protoB\n" +
	"GreetProtoP\x01Z3github.com/openimsdk/protocol/city/proto;city_protob\x06proto3"

var (
	file_city_proto_mpaaspush_proto_rawDescOnce sync.Once
	file_city_proto_mpaaspush_proto_rawDescData []byte
)

func file_city_proto_mpaaspush_proto_rawDescGZIP() []byte {
	file_city_proto_mpaaspush_proto_rawDescOnce.Do(func() {
		file_city_proto_mpaaspush_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_city_proto_mpaaspush_proto_rawDesc), len(file_city_proto_mpaaspush_proto_rawDesc)))
	})
	return file_city_proto_mpaaspush_proto_rawDescData
}

var file_city_proto_mpaaspush_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_city_proto_mpaaspush_proto_goTypes = []any{
	(*GreetRequest)(nil),     // 0: city_proto.GreetRequest
	(*GreetResponse)(nil),    // 1: city_proto.GreetResponse
	(*SayHelloRequest)(nil),  // 2: city_proto.SayHelloRequest
	(*SayHelloResponse)(nil), // 3: city_proto.SayHelloResponse
}
var file_city_proto_mpaaspush_proto_depIdxs = []int32{
	0, // 0: city_proto.GreetService.Greet:input_type -> city_proto.GreetRequest
	2, // 1: city_proto.GreetService.SayHello:input_type -> city_proto.SayHelloRequest
	1, // 2: city_proto.GreetService.Greet:output_type -> city_proto.GreetResponse
	3, // 3: city_proto.GreetService.SayHello:output_type -> city_proto.SayHelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_city_proto_mpaaspush_proto_init() }
func file_city_proto_mpaaspush_proto_init() {
	if File_city_proto_mpaaspush_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_city_proto_mpaaspush_proto_rawDesc), len(file_city_proto_mpaaspush_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_city_proto_mpaaspush_proto_goTypes,
		DependencyIndexes: file_city_proto_mpaaspush_proto_depIdxs,
		MessageInfos:      file_city_proto_mpaaspush_proto_msgTypes,
	}.Build()
	File_city_proto_mpaaspush_proto = out.File
	file_city_proto_mpaaspush_proto_goTypes = nil
	file_city_proto_mpaaspush_proto_depIdxs = nil
}
