// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: push/push.proto

package push

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IMPushMsgService_PushMsg_FullMethodName          = "/openim.push.IMPushMsgService/PushMsg"
	IMPushMsgService_DelUserPushToken_FullMethodName = "/openim.push.IMPushMsgService/DelUserPushToken"
)

// IMPushMsgServiceClient is the client API for IMPushMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IMPushMsgServiceClient interface {
	PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error)
	DelUserPushToken(ctx context.Context, in *DelUserPushTokenReq, opts ...grpc.CallOption) (*DelUserPushTokenResp, error)
}

type iMPushMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIMPushMsgServiceClient(cc grpc.ClientConnInterface) IMPushMsgServiceClient {
	return &iMPushMsgServiceClient{cc}
}

func (c *iMPushMsgServiceClient) PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushMsgResp)
	err := c.cc.Invoke(ctx, IMPushMsgService_PushMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMPushMsgServiceClient) DelUserPushToken(ctx context.Context, in *DelUserPushTokenReq, opts ...grpc.CallOption) (*DelUserPushTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelUserPushTokenResp)
	err := c.cc.Invoke(ctx, IMPushMsgService_DelUserPushToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMPushMsgServiceServer is the server API for IMPushMsgService service.
// All implementations must embed UnimplementedIMPushMsgServiceServer
// for forward compatibility.
type IMPushMsgServiceServer interface {
	PushMsg(context.Context, *PushMsgReq) (*PushMsgResp, error)
	DelUserPushToken(context.Context, *DelUserPushTokenReq) (*DelUserPushTokenResp, error)
	mustEmbedUnimplementedIMPushMsgServiceServer()
}

// UnimplementedIMPushMsgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIMPushMsgServiceServer struct{}

func (UnimplementedIMPushMsgServiceServer) PushMsg(context.Context, *PushMsgReq) (*PushMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMsg not implemented")
}
func (UnimplementedIMPushMsgServiceServer) DelUserPushToken(context.Context, *DelUserPushTokenReq) (*DelUserPushTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelUserPushToken not implemented")
}
func (UnimplementedIMPushMsgServiceServer) mustEmbedUnimplementedIMPushMsgServiceServer() {}
func (UnimplementedIMPushMsgServiceServer) testEmbeddedByValue()                          {}

// UnsafeIMPushMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMPushMsgServiceServer will
// result in compilation errors.
type UnsafeIMPushMsgServiceServer interface {
	mustEmbedUnimplementedIMPushMsgServiceServer()
}

func RegisterIMPushMsgServiceServer(s grpc.ServiceRegistrar, srv IMPushMsgServiceServer) {
	// If the following call pancis, it indicates UnimplementedIMPushMsgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IMPushMsgService_ServiceDesc, srv)
}

func _IMPushMsgService_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMPushMsgServiceServer).PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMPushMsgService_PushMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMPushMsgServiceServer).PushMsg(ctx, req.(*PushMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMPushMsgService_DelUserPushToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserPushTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMPushMsgServiceServer).DelUserPushToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMPushMsgService_DelUserPushToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMPushMsgServiceServer).DelUserPushToken(ctx, req.(*DelUserPushTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IMPushMsgService_ServiceDesc is the grpc.ServiceDesc for IMPushMsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMPushMsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.push.IMPushMsgService",
	HandlerType: (*IMPushMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMsg",
			Handler:    _IMPushMsgService_PushMsg_Handler,
		},
		{
			MethodName: "DelUserPushToken",
			Handler:    _IMPushMsgService_DelUserPushToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push/push.proto",
}
